ssoServiceUrl: http://localhost:8080/uaa
server:
  port: 9999
spring:
  thymeleaf:
    cache: false
security:
  basic:
  oauth2:
    client:
      client-id: resource1
      client-secret: resource1
      grant-type: client_credentials
      scope: 
        - resource.read
        - resource.write
      access-token-uri: ${ssoServiceUrl}/oauth/token
      user-authorization-uri: ${ssoServiceUrl}/oauth/authorize
    resource:
      token-info-uri: ${ssoServiceUrl}/oauth/check_token
      jwt:
        key-uri: ${ssoServiceUrl}/token_key
      user-info-uri: ${ssoServiceUrl}/userinfo
      id: resource

logging.level:
  org.springframework.security: DEBUG